-- MySQL Script generated by MySQL Workbench
-- Sat Dec 15 01:09:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `dadosAlunos` DEFAULT CHARACTER SET utf8 ;
USE dadosAlunos ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `senha` VARCHAR(30) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS aluno (
  `iddados_pessoais` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `sexo` VARCHAR(10) NULL,
  `nascimento` date NULL,
  `cpf` int NULL,
  `matricula` int NULL,
  PRIMARY KEY (`iddados_pessoais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS professor (
  `idprofessor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` int NULL,
  `rg` int NULL,
  `sexo` VARCHAR(10) NULL,
  `nascimento` date NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS disciplinas (
  `iddisciplinas` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `professor_idprofessor` INT NOT NULL,
  PRIMARY KEY (`iddisciplinas`, `professor_idprofessor`),
  INDEX `fk_disciplinas_professor_idx` (`professor_idprofessor` ASC) VISIBLE,
  CONSTRAINT `fk_disciplinas_professor`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS notas (
  `idnotas` INT NOT NULL,
  `primeiro` VARCHAR(45) NULL,
  `segundo` VARCHAR(45) NULL,
  `terceiro` VARCHAR(45) NULL,
  `quarto` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `disciplinas_iddisciplinas` INT NOT NULL,
  `disciplinas_professor_idprofessor` INT NOT NULL,
  `aluno_iddados_pessoais` INT NOT NULL,
  PRIMARY KEY (`idnotas`, `disciplinas_iddisciplinas`, `disciplinas_professor_idprofessor`, `aluno_iddados_pessoais`),
  INDEX `fk_notas_disciplinas1_idx` (`disciplinas_iddisciplinas` ASC, `disciplinas_professor_idprofessor` ASC) VISIBLE,
  INDEX `fk_notas_aluno1_idx` (`aluno_iddados_pessoais` ASC) VISIBLE,
  CONSTRAINT `fk_notas_disciplinas1`
    FOREIGN KEY (`disciplinas_iddisciplinas` , `disciplinas_professor_idprofessor`)
    REFERENCES `mydb`.`disciplinas` (`iddisciplinas` , `professor_idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_aluno1`
    FOREIGN KEY (`aluno_iddados_pessoais`)
    REFERENCES `mydb`.`aluno` (`iddados_pessoais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
